// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2025 Pierre Fitness Intelligence

import { useQuery } from '@tanstack/react-query';
import type { WellnessSummary } from '../types/wellness';

// Track when a manual refresh was performed so we skip the static file
// (which may contain stale data) and go straight to the API.
let lastManualRefreshTs = 0;

export function markManualRefresh() {
  lastManualRefreshTs = Date.now();
}

async function fetchWellnessData(): Promise<WellnessSummary> {
  const skipStaticFile = Date.now() - lastManualRefreshTs < 30 * 60 * 1000;

  // Try static file first (generated by fetch_garmin_live.py with rich data)
  // but only if no manual refresh was done recently
  if (!skipStaticFile) {
    try {
      const staticRes = await fetch('/data/wellness_summary.json');
      if (staticRes.ok) {
        const data = await staticRes.json();
        // Validate it has real data (not empty)
        if (data?.latest && data?.days?.length > 0) {
          return data;
        }
      }
    } catch {
      // Static file not available, fall through to API
    }
  }

  // Fallback to API endpoint
  const token = localStorage.getItem('auth_token');
  const headers: HeadersInit = {
    'Content-Type': 'application/json',
  };

  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }

  const res = await fetch('/api/wellness/summary', {
    headers,
    credentials: 'include',
  });

  if (!res.ok) {
    throw new Error(`Failed to load wellness data: ${res.status} ${res.statusText}`);
  }

  return res.json();
}

export function useWellnessData() {
  return useQuery<WellnessSummary>({
    queryKey: ['wellness-summary'],
    queryFn: fetchWellnessData,
    staleTime: 30 * 60 * 1000,      // 30 min: data stays "fresh" longer
    gcTime: 60 * 60 * 1000,          // 1h: keep in cache even without subscribers
    refetchOnMount: false,            // Don't refetch when component remounts
    refetchOnWindowFocus: false,      // Don't refetch on window/tab focus
    retry: 2,
  });
}
