// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2025 Pierre Fitness Intelligence

import { useQuery } from '@tanstack/react-query';
import type { WellnessSummary } from '../types/wellness';

async function fetchWellnessData(): Promise<WellnessSummary> {
  // Try static file first (generated by fetch_garmin_live.py with rich data)
  try {
    const staticRes = await fetch('/data/wellness_summary.json');
    if (staticRes.ok) {
      const data = await staticRes.json();
      // Validate it has real data (not empty)
      if (data?.latest && data?.days?.length > 0) {
        return data;
      }
    }
  } catch {
    // Static file not available, fall through to API
  }

  // Fallback to API endpoint
  const token = localStorage.getItem('auth_token');
  const headers: HeadersInit = {
    'Content-Type': 'application/json',
  };

  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }

  const res = await fetch('/api/wellness/summary', {
    headers,
    credentials: 'include',
  });

  if (!res.ok) {
    throw new Error(`Failed to load wellness data: ${res.status} ${res.statusText}`);
  }

  return res.json();
}

export function useWellnessData() {
  return useQuery<WellnessSummary>({
    queryKey: ['wellness-summary'],
    queryFn: fetchWellnessData,
    staleTime: 2 * 60 * 1000,
    refetchInterval: 5 * 60 * 1000,
    retry: 2,
  });
}
